# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  catalogserver:
    image: catalogserver
    build: 
      context: .
      dockerfile: src/Services/Catalog/Dockerfile
    ports:
      - 5056:5056
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
  hangfireserver:
    image: hangfireserver
    build:
      context: .
      dockerfile: src/Services/HangFire/Dockerfile
    ports:
      - 5055:5055
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
  identityserver:
    image: identityserver
    build: 
      context: .
      dockerfile: src/Services/Identity/Dockerfile
    ports:
        - 5057:5057
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
