# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  hangfireserver:
    image: hangfireserver
    build:
      context: .
      dockerfile: src/Services/HangFireServer/Dockerfile
    ports:
      - 5286:5286
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
  identity:
    image: identity
    build:
      context: .
      dockerfile: src/Services/Identity/Identity.API/Dockerfile
    ports:
      - 5287:5287
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080