# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  catalog:
    image: catalog
    build:
      context: .
      dockerfile: src/Services/Catalog/Dockerfile
    ports:
      - 5055:5055
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
  hangfire:
    image: hangfire
    build:
      context: .
      dockerfile: src/Services/HangFire/Dockerfile
    ports:
      - 5056:5056
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
  identity:
    image: identity
    build:
      context: .
      dockerfile: src/Services/Identity/Dockerfile
    ports:
      - 5057:5057
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw