name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build and Publish Hangfire Server
        run: dotnet publish -c Release -o ./publish
        working-directory: ./src/Services/HangFireServer
        
      - name: Build and Publish Identity
        run: dotnet publish -c Release -o ./publish
        working-directory: ./src/Services/Identity/Identity.API
      
      - name: Build and Publish Portal
        run: dotnet publish -c Release -o ./publish
        working-directory: ./src/Services/Portal/Portal.API
        
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2 
      - name: Build & Deploy
        env:
            PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
            HOSTNAME: ${{secrets.HOST_DNS}}
            USER_NAME: ${secrets.USER_NAME}
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME}
              '
                # Now we have got the access of EC2 and we will start the deploy .
                mkdir helloworld
              '
      - name: Update repository source on EC2 instance
        run: |
          ssh -i ${{ secrets.SSH_PRIVATE_KEY }} {{secrets.EC2_HOST}} 'cd /zaeshop && git pull'

      - name: Build and push Docker images
        run: |
          ssh -i ${{ secrets.SSH_PRIVATE_KEY }} {{secrets.EC2_HOST}} 'cd /zaeshop && docker-compose build --parallel'
          ssh -i ${{ secrets.SSH_PRIVATE_KEY }} {{secrets.EC2_HOST}} 'cd /zaeshop && docker-compose push'
          
      - name: Connect to EC2 instance and run Docker Compose
        run: |
          ssh -i ${{ secrets.SSH_PRIVATE_KEY }} {{secrets.EC2_HOST}} 'cd /zaeshop && docker-compose down && docker-compose pull && docker-compose up -d'

