name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build and Publish Hangfire Server
        run: dotnet publish -c Release -o ./publish
        working-directory: ./src/Services/HangFireServer
        
      - name: Build and Publish Identity
        run: dotnet publish -c Release -o ./publish
        working-directory: ./src/Services/Identity/Identity.API
      
      - name: Build and Publish Portal
        run: dotnet publish -c Release -o ./publish
        working-directory: ./src/Services/Portal/Portal.API

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH for CentOS
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          
      - name: Test SSH Connection
        run: |
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.SSH_PRIVATE_KEY }} ${{ secrets.EC2_HOST }} echo "SSH connection successful"

      - name: Deploy to AWS EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.SSH_PRIVATE_KEY }} ${{ secrets.EC2_HOST }} 'bash -s' < deploy.sh
