name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build and Publish Hangfire Server
        run: dotnet publish -c Release -o ./publish
        working-directory: ./src/Services/HangFireServer
        
      - name: Build and Publish Identity
        run: dotnet publish -c Release -o ./publish
        working-directory: ./src/Services/Identity/Identity.API
      
      - name: Build and Publish Portal
        run: dotnet publish -c Release -o ./publish
        working-directory: ./src/Services/Portal/Portal.API
        
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: SSH into EC2 instance
        uses: appleboy/ssh-action@master
        with:
          host: your-ec2-instance-ip
          username: your-ec2-instance-username
          key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Update repository source on EC2 instance
        run: |
          ssh -i ${{ secrets.SSH_PRIVATE_KEY }} {{secrets.EC2_HOST}} 'cd /zaeshop && git pull'

      - name: Build and push Docker images
        run: |
          ssh -i ${{ secrets.SSH_PRIVATE_KEY }} {{secrets.EC2_HOST}} 'cd /zaeshop && docker-compose build --parallel'
          ssh -i ${{ secrets.SSH_PRIVATE_KEY }} {{secrets.EC2_HOST}} 'cd /zaeshop && docker-compose push'
          
      - name: Connect to EC2 instance and run Docker Compose
        run: |
          ssh -i ${{ secrets.SSH_PRIVATE_KEY }} {{secrets.EC2_HOST}} 'cd /zaeshop && docker-compose down && docker-compose pull && docker-compose up -d'

